# Generated by Django 4.0.3 on 2022-03-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
